### ISSUE TITLE
(Front) Data with no lat/long breaks Mapeo web

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-webmaps#35]
[**Description**
](https://www.notion.so/digidem/Data-with-no-lat-long-breaks-Mapeo-web-47f2cb6a60da4108970aa9eabf1f81bb)Currently, it is possible to create data in Mapeo Mobile without any coordinates. When this data is synced with Mapeo Desktop Observations, and then included in an export to Webmap, it breaks the webmap interface by throwing an error `Uncaught TypeError: Invalid attempt to destructure non-iterable instance` (stacktrace pointing to [this line](https://github.com/digidem/mapeo-webmaps-public/blob/87736258dcfe3a31bca6c1fb5614f062f5f3c019/views/map.js#L278)). 

**This results in a number of errors:**

- Sometimes the satellite background layer (as set by the user) doesn't load
- Sometimes the title and description don't load
- Sometimes clicking the stories doesn't result in the map panning to that point
- The map doesn't zoom to the maximum extent of the points by default (fitBounds)
- The popups don't align with the points on the map
- Clicking the points doesn't do anything
- Sometimes the points don't show up on load

**To reproduce this behavior,**

1. Turn off the GPS on a device with Mapeo Mobile
2. Create a data point on that device's Mobile Mobile and bypass the "No GPS signal" warning screen by pressing Save.
3. Sync your data with Mapeo Desktop.
4. From Mapeo Desktop Observations, export a webmap.
5. Add this webmap on a [https://maps.mapeo.app](https://maps.mapeo.app) account.
6. See errors on the webmap public link.

**Suggested fix:**

Filter the data array on the front end to remove any data with no coordinates (or coordinates that are outside of an expected lat/long range). Or, only showing these data as cards in the sidebar, but omitting them from the map.

This is in lieu of what is likely to be a larger discussion on handling data without coordinates across Mapeo apps.

**Todo:**
Filter the data array on the front end to remove any data with no coordinates (or coordinates that are outside of an expected lat/long range)

**Comment by ErikSin** [comment]
This is in the wrong repo!

**Comment by achou11** [comment]
> This is in the wrong repo!

Ah yeah it should be added to https://github.com/digidem/mapeo-webmaps-public instead. Will port this issue over

**Comment by achou11** [comment]
Refer to https://github.com/digidem/mapeo-webmaps-public/issues/14
