### ISSUE TITLE
Admin - No Map

### ISSUE THREAD

**Issue by ximenabb** [digidem/mapeo-webmaps#54]
### Description
User has successfully logged in. It is the user's first time on the page or had not created a map yet

### Screen
Navigation bar - LEFT
(Add Map +)

Navigation bar - RIGHT
(Email address of user) / Logout

BODY
No maps to show
Export data from **[Mapeo Deskop](https://docs.mapeo.app/quick-start-guide/mapeo-desktop)** to share publicly
Not sure how to add maps? **[Go to Tutorials](https://docs.mapeo.app/complete-reference-guide/mapeo-desktop-use/using-mapeo-desktop-to-manage-mapeo-mobile-data/exporting-and-sharing-externally#export-as-web-map)**
Add Map+
***note Ximena - @rudokemper  can you confirm this is the links we want it to redirect to?**

### Tech specs
To specify accepted files and error flows ?
- @ErikSin find specific file type

### Copydeck
https://docs.google.com/spreadsheets/d/1XV5JWBst476U9O5zNyqFeGAT5MSXbxlWHwiinG49BzI/edit#gid=1955026440

### Design
<img width="555" alt="Screen Shot 2022-11-14 at 4 39 49 PM" src="https://user-images.githubusercontent.com/78557542/201771198-e7623851-2409-4fe6-9044-bf9665bf68f3.png">

Prototype - https://www.figma.com/proto/fk0kK8cdXX1Vs9JCWRSdVh/In-Progress?node-id=620%3A291&scaling=min-zoom&page-id=603%3A288&starting-point-node-id=603%3A289&hide-ui=1

<img width="716" alt="Screen Shot 2022-11-17 at 11 37 05 AM" src="https://user-images.githubusercontent.com/78557542/202504932-ffb086a3-77c1-4cbe-918f-594b876dd91a.png">

Figma - https://www.figma.com/file/fk0kK8cdXX1Vs9JCWRSdVh/In-Progress?node-id=603%3A288

**Comment by rudokemper** [comment]
@ximenabb yep that link is good! 👍
